<nav class="navbar-solid">
  <a class="logo" href="index.php">SwinWORK</a>
  <div class="navbar__link-container">
    <a href="services.php" class="navbar__link">Services</a>
    <a href="jobs.php" class="navbar__link">Career</a>
    <a href="about.php" class="navbar__link">About</a>
  </div>
  <div class="navbar__btn-container">
    <a href="login.php" class="btn btn-outline">Login</a>

    <input type="checkbox" class="navigation__checkbox" id="nav-toggle" />
    <label for="nav-toggle" class="navigation__button">
      <span class="navigation__icon">&nbsp;</span>
    </label>

    <div class="navigation__background">&nbsp;</div>

    <nav class="navigation__nav">
      <ul class="navigation__list">
        <li class="navigation__item">
          <a href="services.php" class="navbar__link">Services</a>
        </li>
        <li class="navigation__item">
          <a href="jobs.php" class="navbar__link">Career</a>
        </li>
        <li class="navigation__item">
          <a href="apply.php" class="navbar__link">Apply</a>
        </li>
        <li class="navigation__item">
          <a href="about.php" class="navbar__link">About</a>
        </li>
      </ul>
    </nav>
  </div>
</nav>
